#!/bin/bash

DEFAULT_CONFIG_PATH="$HOME/.config/ssht/ssht.yml"

declare -A tunnel_params

main() {
    parse_args $@

    # If no file is specified the default file is chosen
    if [ -z "$FILE" ] ; then
        FILE=$DEFAULT_CONFIG_PATH
    fi

    run_command $@
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -f|--file)
                FILE="$2"
                shift # past argument
                shift # past value
            ;;
            -*|--*)
                echo "Unknown option $1"
                exit 3
            ;;
            *)
                POSITIONAL_ARGS+=("$1") # save positional arg
                shift # past argument
            ;;
        esac
    done
}

run_command() {
    command=$1
    case $command in
        "") help::main ;;
        "open")  open_tunnel  $@ ;;
        "close") close_tunnel $@ ;;
        "status") status ${@:2} ;;
        "show") show  ;;
        "list") list  ;;
        "help") help ${@:2}  ;;
        *) 
            echo "Error - Command not found." 
            print_available_commands
        ;;
    esac
}


open_tunnel() {
    if [ ${#POSITIONAL_ARGS[@]} -gt 2 ]; then
        error::too_many_params
    fi

    command=$1
    process_name=$2


    if [ -z $process_name ] ; then
        open_all_tunnels
        exit 0
    fi

    read_config $command $process_name $FILE

    key=""
    if [ -n "${tunnel_params['ssh_key_path']}" ]; then
        key="-i ${tunnel_params['ssh_key_path']}"
    fi

    ssh_cmd="ssh -N -L ${tunnel_params['port_forward']}:${tunnel_params['host_destination']}:${tunnel_params['port_destination']} ${tunnel_params['user_server']}@${tunnel_params['host_server']} -f $key"
    echo "Running: $ssh_cmd"
    eval $ssh_cmd
}

open_all_tunnels() {
        all_configs=$(yq '.tunnels | keys | .[]' $FILE)
        for config in $all_configs ; do
            read_config $command $config $FILE
            open_tunnel $command $config
        done
}

read_config() {
    cmd=$1
    process_name=$2

    while IFS="=" read -r key value; do tunnel_params["$key"]=$value; done < <(
        yq ".tunnels.\"$process_name\" | to_entries | map([.key, .value] | join(\"=\")) | .[]" $FILE
    )

    if [ ${#tunnel_params[@]} -eq 0 ] ; then
        error::process_name_not_found $2
    fi
}
error::process_name_not_found() {
    >&2 echo "Error - The name \"$1\" couldn't be found in the config file."
    echo "Use \"ssht list\" to display the available tunnels."
    exit 1
}


close_tunnel() {
    if [ ${#POSITIONAL_ARGS[@]} -gt 2 ]; then
        error::too_many_params
    fi

    command=$1
    process_name=$2

    if [ -z $process_name ] ; then
        close_all_tunnels
        exit 0
    fi

    read_config $command $process_name $FILE
    cmd="fuser ${tunnel_params['port_forward']}/tcp -k"
    echo "Running (killing the process_name): $cmd"
    eval $cmd
}

close_all_tunnels() {
    all_configs=$(yq '.tunnels | keys | .[]' $FILE)
    for config in $all_configs ; do
        read_config $command $config $FILE
        close_tunnel $command $config
    done
}

status_all() {
    
    # echo -e "Format: ${GREEN}open${NC} | ${RED}closed${NC}\n"

    all_configs=$(yq '.tunnels | keys | .[]' $FILE)
    for config in $all_configs ; do
        result=$(status $config)
        case "$result" in
            "open")   color=$GREEN ;;
            "closed") color=$RED ;;
        esac
        echo "- $config:"
        echo "  $result"
        
    done
}

status() {
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m' # No Color

    process_name=$1

    if [ -z $process_name ] ; then
        status_all
        exit 0
    fi

    port=$(yq ".tunnels.\"$process_name\".port_forward" $FILE)
    if [[ $port == "null" ]] ; then
        error::process_name_not_found $2
    fi

    if [ -n "$(lsof -i tcp:$port)"  ] ; then
        echo -e "${GREEN}open${NC}"
    else
        echo -e "${RED}closed${NC}"
    fi
    
}

show() {
    if [ ${#POSITIONAL_ARGS[@]} -gt 1 ]; then
        error::too_many_params
    fi

    yq $FILE
}

list() {
    if [ ${#POSITIONAL_ARGS[@]} -gt 1 ]; then
        error::too_many_params
    fi

    yq '... comments="" | .tunnels | keys ' $FILE
}

error::too_many_params() {
    >&2 echo "Error - Too many positional params for this command."
    exit 2
}

####################
# HELP FUNCTIONS
####################

help() {
    if [ ${#POSITIONAL_ARGS[@]} -gt 2 ]; then
        error::too_many_params
    fi

    command=$1
    case $command in
        "") help::main  ;;
        "open") help::open  ;;
        "close") help::close  ;;
        "status") help::close  ;;
        "show") help::show  ;;
        "list") help::list  ;;
        *) 
            echo "Error - Command not found." 
            print_available_commands
        ;;
    esac
}

help::main() {
    cat << EOF
Manages SSH tunnels from a YAML configuration.

Usage: 
ssht <command> [-f|--file <file>]

Commands:
    - open [query]    Opens ssh tunnels
    - close [query]   Closes ssh tunnels
    - status [query]
    - show            Shows an ssht.yml configuration
    - list            Lists the available tunnels in the configuration

Options:
    - -f|--file   The configuration file. Default if none is 
                  provided: ~/.config/ssht/ssht.yml

Help with specific command: 
ssht help <command>

Example: 
ssht help open
EOF
}

help::open() {
    cat << EOF
Opens an ssh tunnel from a YAML configuration given an optional query.

Usage:
ssht open [query] [-f|--file <file>]

The query must match the name of some tunnel in your config file.
If no query is provided it will open all the tunnels available.

Examples:
ssht open my_database.prod
ssht open my_database.test -f my-config.yml

The example above is using the ssht.example.yml config file from the repository.
For more info visit: https://github.com/markelca/ssh-tunnels#example
EOF
}

help::status() {
    echo "Status help"
}
help::close() {
    cat << EOF
Closes an ssh tunnel from a YAML configuration given a specific query.

Usage:
ssht close [query] [-f|--file <file>]

The query must match the name of some tunnel in your config file.
If no query is provided it will close all the tunnels available.

Examples:
ssht close my_database.prod
ssht close my_database.test -f my-config.yml

The example above is using the ssht.example.yml config file from the repository.
For more info visit: https://github.com/markelca/ssh-tunnels#example
EOF

}

help::show() {
    cat << EOF
Displays an ssht YAML configuration.

Usage:
ssht show [-f|--file <file>]

Examples:
ssht show
ssht show -f ssht.example.yml

The example above is using the ssht.example.yml config file from the repository.
For more info visit: https://github.com/markelca/ssh-tunnels#example
EOF
}

help::list() {
    cat << EOF
Lists the available ssht tunnels from a YAML configuration.

Usage: 
ssht list [-f|--file <file>]

Examples:
ssht list
ssht list -f ssht.example.yml

The example above is using the ssht.example.yml config file from the repository.
For more info visit: https://github.com/markelca/ssh-tunnels#example
EOF
}

print_available_commands() {
    cat << EOF
The available commands are:
    - open
    - close
    - status
    - show
    - list
EOF
}

main $@
